# Generated by Django 3.1.2 on 2020-10-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('административное', 'Административное право'), ('уголовное', 'Уголовное право'), ('исполнительное', 'Исполнительное производство')], default='административное', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.SlugField(max_length=250, unique='publish'),
        ),
    ]
